-- SCRIPT BUAT SEQUENCE UNTUK PRIMARI KEY
	CREATE SEQUENCE id_rekam_medis;
-- SCRIPT BUAT TABLE REKAM MEDIS
	CREATE TABLE rekam_medis (
	id integer not null default nextval('id_rekam_medis') PRIMARY KEY,
	id_user integer not null,
	diagnosa varchar(20) not null,
	obat integer not null
	)
-- SCRIPT ALTER SEQUENCE
	ALTER SEQUENCE id_rekam_medis OWNED BY rekam_medis.id
-- SCRIPT INSERT INTO REKAM_MEDIS
	INSERT INTO rekam_medis VALUES (nextval('id_rekam_medis'), '1','Sakit Pekala','1')
-- SCRIPT SELECT MELIHAT HASIL INSERT 
	SELECT * FROM rekam_medis

	
-- SCRIPT SEQUENCE OTOMATIS
	CREATE TABLE accounts(
		id INT GENERATED BY DEFAULT AS IDENTITY,
		nama varchar(20) not null,
		balance DEC(18,2) not null,
		primary key(id)
	)


-- SCRIPT OBAT
	CREATE SEQUENCE id_obat
-- SCRIPT TABLE OBAT
	CREATE TABLE obats (
	id INTEGER NOT NULL DEFAULT nextval('id_obat') PRIMARY KEY,
	nama_obat VARCHAR(20),
	harga_obat DECIMAL(18,2)
	)
-- SCRIPT SEQUENCE 
  ALTER SEQUENCE id_obat OWNED BY obats.id
-- SCRIPT INSERT INTO OBAT
	INSERT INTO obats VALUES (nextval('id_obat'), 'parasetamol','2000')
  -- SCRIPT SELECT HASIL INSERT OBAT
	SELECT * FROM obats
  -- SCRIPT JOIN TABLE USERS , REKAM MEDIS , OBAT
  SELECT 
  rm.diagnosa, 
  us.name_users,
  ob.nama_obat,
  ob.harga_obat
  FROM rekam_medis rm
    LEFT JOIN users us on us.id = rm.id_user
    LEFT JOIN obats ob on ob.id = rm.obat

--FOREIGN KEY 
--so item table 1
--so headers table 2
CREATE TABLE so_items (
  item_id INTEGER NOT NULL,   
  so_id INTEGER REFERENCES so_headers(id),
  product_id INTEGER,
  qty INTEGER,
  net_price numeric,
  PRIMARY KEY (item_id,so_id)
);